### PR TITLE
Fix indent problem

### PR DESCRIPTION
**Pull request by henry-hsieh**
1. Fix the indent of 'always @*'
```
  // Original
  always @*
      statement;  // 2 tabs after 'always @*'

  // Modified
  always @*
    statement;
```
2. Change the indent of case item
```
  // Original
  case (exp)
    item0: begin  // No error when case item and 'begin' are on the same line
      statement0;
    end
    item1: // One redundent tab when 'begin' is on the next line after case item
      begin
        statement1;
      end

  // Modified
  case (exp)
    item0: begin  // No error when case item and 'begin' are on the same line
      statement0;
    end
    item1: // No error when 'begin' is on the next line after case item
    begin
      statement1;
    end
```

### CODE REVIEW

**Comment by vhda** [comment]
Thanks for identifying this issue and proposing a fix, but unfortunately this is failing the automatic Travis CI checks. This means that the proposed fix introduces a regression.

Could please I ask you to review this?

Thanks!

**Comment by henry-hsieh** [comment]
I'll try to setup the test environment. When I use the test program, it can't detect the folding status. However, it pass on Travis CI check (folding test).

**Comment by henry-hsieh** [comment]
If there is anything I have to modify, please tell me. @vhda

**Comment by vhda** [comment]
I wasn't able to look into this during the weekend. Will do so as soon as I have a bit more of free time, ok?

**Comment by henry-hsieh** [comment]
That's OK.

**Pull request closed without merging**
