### PR TITLE
Automatic indent test & improved test framework

### PR DESCRIPTION
**Pull request by lewis6991**

### CODE REVIEW

**Comment by vhda** [comment]
The last commit should have been done in a separate Pull Request.

Allow me to fix an indentation issue and then you can rebase the new indent verification code on top of the change.

**Comment by vhda** [comment]
I've just pushed the change that will make the current indent test file to not be modified during an automatic test.
I would kindly ask you to make the following separate commits:
1. Implementation of automatic indentation verification.
2. Fix to the multiple line comment, including the required test.
3. Update of travis-ci configuration.

Take into account that Github follows branches, so if you create a Pull Request in the master branch Github will follow any changes you make to that branch. To avoid possible issues with Github I would advise you to create a new branch before creating the PR, so that you can later make changes to that branch while continuing your development in master.

**Comment by lewis6991** [comment]
Just gone through all the feedback and all seems reasonable. Will try to make the changes tonight (UTC+0).

Only issue I have is that I didn't understand fully what you said about the `*` open statement. Do we keep my change for that or do we revert to the old one?

**Comment by vhda** [comment]
I'm nervous about that `*` change...
Could you check my PR #37?
What do you think of that solution?

**Comment by lewis6991** [comment]
If your solution works for:

``` systemverilog
/*
*
* Comment
*
*/
```

Then I'm more than happy with it. My change was simply the result of trial and error so I'd be nervous too.

Will your solution work if the block comment is indented. I'm not familiar with `synId()` but from what I can tell it takes a column argument so would that mean your solution would only work for non-indented comments due to the column argument of `1`?

Update: I think the column argument `1` will be fine for the comment style I have mentioned.

**Comment by vhda** [comment]
I've just merged the PR, so you can look at the code that I've implemented.
Feel free to provide feedback.

**Pull request closed without merging**
