### PR TITLE
Test: Add errorformat test target

### PR DESCRIPTION
**Pull request by vhda**
This test required redirecting `stdout` to `/dev/null`, so I had to create a separate target in the Makefile. To be coherent I decided to give each test topic a separate make target.

### CODE REVIEW

**Comment by vhda** [comment]
Tests are failing in Travis, for some reason.
I will debug this later.

**Comment by vhda** [comment]
It helps if you don't forget to add files :)

**Comment by vhda** [comment]
@lewis6991 Can I merge this one? I need this to coordinate improvements for #88

**Comment by lewis6991** [comment]
Yeah this one is fine.

**Pull request merged**
