### PR TITLE
Added support for local, protected and static qualifiers on field ins…

### PR DESCRIPTION
**Pull request by lewis6991**
…tances.

### CODE REVIEW

**Comment by vhda** [comment]
Good catch!

But, from what I can gather, all the following qualifiers should be supported:

```
static logic          static_logic;
protected logic       protected_logic;
local logic           local_logic;
const static logic    const_static_logic;
const protected logic const_protected_logic;
const local logic     const_local_logic;
rand logic            rand_logic;
randc logic           randc_logic;
```

So, the pattern should also include an optional `const` and the `rand` or
`randc` alternatives.

**Comment by lewis6991** [comment]
Just checked the 2012 LRM and I think your right, however you can also have:

```
const logic
```

I'll add them all in.

**Comment by vhda** [comment]
Could you please squash all the commits into one?

**Comment by lewis6991** [comment]
My git skills are lacking. What's the best way to do this?

**Comment by vhda** [comment]
Should be something like the following:

```
git rebase -i HEAD~3
# I expect you to have 3 entries in the editor. Replace "pick" with
# "squash" in the last two.
# Save and quit.
# Edit the new squashed commit message.
git push -f the_name_of_your_personal_remote
```

**Comment by lewis6991** [comment]
Thanks. Looks like what I did worked. :)

**Comment by vhda** [comment]
Did you `push -f`? I still can't see the new commit in this PR.

**Comment by lewis6991** [comment]
Yes I did. I can see it.

**Comment by vhda** [comment]
I was able to see it after doing a page refresh.
Strange, typically github shows the new commit between the conversation entries... anyway... it's here and I will merge it! :)

Thanks for your help. Keep it coming.

**Pull request merged**
