### PR TITLE
test: Automatic indent test.

### PR DESCRIPTION
**Pull request by lewis6991**

### CODE REVIEW

**Comment by vhda** [comment]
Strange, I see no changes when indenting within an interactive vim session.

**Comment by lewis6991** [comment]
Is it using the right vimrc?

**Comment by lewis6991** [comment]
Travis passes on my remote so I guess the test infrastructure is messing up.

https://travis-ci.org/lewis6991/verilog_systemverilog.vim

**Comment by vhda** [comment]
Create a separate PR for your changes to the travis configuration file.
Let's merge those in first and we'll get back to this one afterwards.
I think it is related with the use of vim-plug.

**Comment by vhda** [comment]
Try rebasing over my latest master and force pushing your changes into your Github repo.

**Comment by lewis6991** [comment]
Woo!

**Comment by vhda** [comment]
There we go :)
Plug would always install MY master branch. I should have seen that coming! eheh

**Pull request merged**
