### PR TITLE
Fix issue 69.

### PR DESCRIPTION
**Pull request by lewis6991**
I'm not too sure if I'm fully happy with this but at least it works.

### CODE REVIEW

**Comment by lewis6991** [comment]
Rebased

**Comment by vhda** [comment]
What about requiring `\(#\?(\|;\)` after the module, interface, class, etc name?
If the interface is the last item of the port list it will not have a comma.

**Comment by lewis6991** [comment]
I realised that too but it doesn't matter because `);` is indented based on `(`. Unless you can think of an example that breaks the script, I don't think there is a need to require anything extra.

**Comment by vhda** [comment]
Only this scenario comes to mind: https://github.com/vhda/verilog_systemverilog.vim/tree/issue/69

**Comment by vhda** [comment]
@lewis6991 did you have the opportunity to look at my branch above? Could you compare both solutions and choose one?

**Comment by lewis6991** [comment]
I did glimpse at it. I'm kinda torn which one to choose, but I think I'm leaning towards my solution as it seems to only break for the example you provided but it wouldn't break much and would recover which I think is fine for such a niche case.

**Comment by lewis6991** [comment]
Using my solution with your scenario (that breaks indentation) yields the indent:

``` systemverilog
module dut_wrapper (
    interface source_IF,
    interface source_IF
        `ifdef TEST
            ,
            interface ctrl_IF
        `endif
):

endmodule
```

It may be incorrect, but it isn't ugly.

With your solution all interfaces have be be written with either `#`, `;` or `(` at the end of the line which is more restrictive.

I think as this solution is less restrictive I prefer it. What do you think?

**Comment by vhda** [comment]
I've been seeing some code where port lists are declared as following:

``` SystemVerilog
module dut_wrapper (
    interface source_IF
  , interface source_IF
    `ifdef TEST
  , interface ctrl_IF
    `endif
);
```

Online example [here](http://www.project-veripage.com/interface_1.php). Whereas, I've never seen a declaration of an interface that does not have a `#`, `;` or a `(` immediately following it. Even though we do not support the `, input name` kind of port list not having a comma at the end is more common than the alternative I'm proposing. That is why I'm so reluctant with your proposal.

**Comment by lewis6991** [comment]
Do you not think this is common?

``` systemverilog
interface some_interface
(
    input clk,
    input reset_n,
    input a,
    output b
);
endinterface
```

Requiring `(;#` would break the indentation of everything within the interface as well as `endinterface`.

**Comment by vhda** [comment]
Personally, I've never seen it. But if you tell me you have I will not contest your solution any longer.

**Comment by vhda** [comment]
Please rebase this PR and I'll merge.

**Comment by NicoLugil** [comment]
Note that when I originally submitted this issue, the focus is on the generic interface, which is a sv feature allowing to just say it is an interface. I.e in my example code the interfaces are defined using (, etc... But these don't need to be mentioned in the module.

**Comment by lewis6991** [comment]
@NicoLugil Yes we understand this, but thanks for clarifying. The issue we are having is being able to differentiate between generic interfaces and interface block declarations.

**Comment by lewis6991** [comment]
@vhda I don't think any of the scenarios we have said are common. My only concern is trying to break as little as possible.

**Comment by vhda** [comment]
Let's advance with your solution. We can revisit this later of if we ever need to, don't worry! :)

**Comment by vhda** [comment]
Thanks @lewis6991

**Pull request merged**
